### ISSUE TITLE
What's the relationship between paragraphs and entries in this class?

### ISSUE THREAD

**Issue by ghost** [zachscrivena/simple-resume-cv#9]
Hello! 

First of all, thank you for your great work. I absolutely love this template.

But I do have a small question.

What's the relationship between paragraphs and entries?
Shall I put several entries into one paragraph, or several paragraphs into one entry?

The first seems illogical, since entries are typically semanticaly larger than paragraphs. The second increases the likelihood of a page break within a job description, which is not very nice to read. 

How did you design it originally?

**Comment by zachscrivena** [comment]
Thank you for the question! I'm glad you found this template useful.

I have included some brief usage notes related to this point in the CV.tex file (see the [compiled CV.pdf](https://raw.githubusercontent.com/zachscrivena/simple-resume-cv/master/CV.pdf)). Each "entry" should typically be accompanied by one "paragraph" --- we use the "entry" macros (\Entry, \BulletItem, \SubBulletItem, \SubSubBulletItem, \Item, \SubItem, \SubSubItem, \NumberedItem) to set up the paragraph indentation so that the "paragraph" of text that comes immediately after the macro is indented at the correct level.

Page breaks should only occur between paragraphs, not within a paragraph. If you have a very long entry/paragraph that you _would_ like to break across pages, you can split up the original paragraph into multiple entries/paragraphs and use the non-bullet "entry" macros (\Entry, \Item, \SubItem, \SubSubItem) to get matching indentation. You can also force page breaks using \newpage if needed.

Hope this clarifies the use of entries and paragraphs in the template. Do let me know if you have further questions.
